# Generated by Django 4.1.3 on 2022-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tvshow_users_favlist_tvshow_users_watchedlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Romancemovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('plot', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('cast', models.JSONField(default='{}')),
                ('image', models.CharField(max_length=100000, null=True)),
                ('meta_rating', models.CharField(max_length=100)),
                ('vote', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
